- name: See if my custom GNOME Terminal profile exists
  ansible.builtin.shell:
    cmd: gsettings get org.gnome.Terminal.ProfilesList list
  changed_when: false
  register: gnome_profiles

- name: Run configuration script
  when: "'aaaaaaaa' not in gnome_profiles.stdout"
  ansible.builtin.shell:
    cmd: "{{ ansible_facts.user_dir }}/.local/bin/configure-gnome-terminal.sh"
